name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  prek:
    uses: ShipSoft/.github/.github/workflows/prek.yml@main
  commit-check:
    permissions:
      contents: read
      pull-requests: write
    uses: ShipSoft/.github/.github/workflows/commit-check.yml@main
